### PR TITLE
Fix build

### PR DESCRIPTION
**Pull request by kelvie**
no_coverage was changed it appears, and one of the libraries stopped building against nightly as well.

### CODE REVIEW

**Comment by twitchax** [comment]
Hey: thanks!

I had actually _just_ done this.  I don't mean to step on this or "block" your contribution, but can you please sync, and see if there are still changes to be made?

**Comment by kelvie** [comment]
I shall try now! Thanks for fixing it!

Great library by the way!

**Comment by kelvie** [comment]
Works great! Can't wait for the next release/tag!

**Comment by twitchax** [comment]
Looks like the action is still broken, so I will look into it.

Yeah, I actually planned to start doing some more experimenting on this library, especially the ML portions, so I will likely ship another release soon-ish.

**Pull request closed without merging**
